version: '3'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234

    volumes:
      - social-media:/var/lib/postgresql/data

    networks:
      - social-media

  app:
    build: .

    depends_on:
      - db

    environment:
      - DB_PASS=1234
      - DB_USER=postgres
      - DB_NAME=postgres
      - DB_HOST=db

    ports:
      - 3000:3000

    networks:
      - social-media

    command: >
      sh -c "npm run docker:env -- npm run schema:sync
      && npm run docker:env -- npm run start"

volumes:
  social-media:

networks:
  social-media:
